apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: limsangwoon/kk
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
