apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: django
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: django
~
